package share

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"text/template"

	"github.com/bng147/gonas/internal/cmdrunner"
)

// NFSClientRule 描述「哪些用戶端」可以用什麼選項掛載一個 export。
// CIDR 留空代表 "*"（任何人都能掛，只有在受信任的家用區網才建議這樣做,
// Web UI 的表單應該預設要求填一個實際的網段)。
type NFSClientRule struct {
	CIDR    string   `json:"cidr,omitempty"`
	Options []string `json:"options"` // 例如 ["rw", "sync", "no_subtree_check"]
}

// Export 描述一個 NFS 匯出目錄。
type Export struct {
	Path    string          `json:"path"`
	Clients []NFSClientRule `json:"clients"`
}

func (e Export) Validate() error {
	if e.Path == "" {
		return fmt.Errorf("nfs export: path is required")
	}
	if len(e.Clients) == 0 {
		return fmt.Errorf("nfs export %q: at least one client rule is required (unrestricted exports are not generated by design)", e.Path)
	}
	for _, c := range e.Clients {
		if len(c.Options) == 0 {
			return fmt.Errorf("nfs export %q: client rule for %q has no options", e.Path, clientLabel(c.CIDR))
		}
	}
	return nil
}

func clientLabel(cidr string) string {
	if cidr == "" {
		return "*"
	}
	return cidr
}

const exportsTemplate = `# 由 GoNAS 自動產生，請勿手動修改 —— 修改請透過 Web UI 或 API。
{{range .}}{{$path := .Path}}{{range .Clients}}{{$path}} {{clientLabel .CIDR}}({{join .Options ","}})
{{end}}{{end}}`

var exportsTmpl = template.Must(template.New("gonas.exports").Funcs(template.FuncMap{
	"join":        strings.Join,
	"clientLabel": clientLabel,
}).Parse(exportsTemplate))

// GenerateExportsConfig 依 export 清單產生 /etc/exports 格式的內容,
// 放進 /etc/exports.d/gonas.exports(現代 nfs-utils 支援的 drop-in 目錄,
// 不需要碰系統原本的 /etc/exports)。
func GenerateExportsConfig(exports []Export) (string, error) {
	for _, e := range exports {
		if err := e.Validate(); err != nil {
			return "", fmt.Errorf("refusing to generate nfs exports config: %w", err)
		}
	}
	var buf bytes.Buffer
	if err := exportsTmpl.Execute(&buf, exports); err != nil {
		return "", fmt.Errorf("rendering exports config: %w", err)
	}
	return buf.String(), nil
}

// ReloadNFS 重新讀取匯出清單並套用，不需要重啟 nfs-server(重啟會讓所有
// 已掛載的用戶端暫時斷線)。
func ReloadNFS(ctx context.Context, r cmdrunner.Runner) error {
	if _, err := r.Run(ctx, "exportfs", "-ra"); err != nil {
		return fmt.Errorf("reloading nfs exports: %w", err)
	}
	return nil
}
