package share

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"text/template"

	"github.com/bng147/gonas/internal/cmdrunner"
)

// NFSClientRule 描述「哪些用戶端」可以用什麼選項掛載一個 export。
// CIDR 留空代表 "*"（任何人都能掛，只有在受信任的家用區網才建議這樣做,
// Web UI 的表單應該預設要求填一個實際的網段)。
type NFSClientRule struct {
	CIDR    string   `json:"cidr,omitempty"`
	Options []string `json:"options"` // 例如 ["rw", "sync", "no_subtree_check"]
}

// Export 描述一個 NFS 匯出目錄。
type Export struct {
	Path    string          `json:"path"`
	Clients []NFSClientRule `json:"clients"`
}

func (e Export) Validate() error {
	if e.Path == "" {
		return fmt.Errorf("nfs export: path is required")
	}
	// 第三十三輪:/etc/exports 是「path client(opts) ...」這種以空白、括號、
	// 逗號分隔的格式,而這個檔案一樣是 text/template 產生的(不跳脫)。
	// 換行會注入額外的 export 行,空白會把單一路徑拆成「路徑 + 用戶端」而
	// 整行語意錯亂,所以 NFS 路徑除了不能有控制字元、也不能有空白。
	if hasControlChars(e.Path) || strings.ContainsAny(e.Path, " \t") {
		return fmt.Errorf("nfs export %q: path cannot contain spaces, line breaks, or control characters", e.Path)
	}
	if len(e.Clients) == 0 {
		return fmt.Errorf("nfs export %q: at least one client rule is required (unrestricted exports are not generated by design)", e.Path)
	}
	for _, c := range e.Clients {
		// CIDR 與 options 都是 export 行裡以空白/括號/逗號界定的欄位,同理
		// 不能含這些界定字元或控制字元,否則會破壞格式或注入額外選項。
		if hasControlChars(c.CIDR) || strings.ContainsAny(c.CIDR, " \t()") {
			return fmt.Errorf("nfs export %q: client %q cannot contain spaces, parentheses, or control characters", e.Path, c.CIDR)
		}
		if len(c.Options) == 0 {
			return fmt.Errorf("nfs export %q: client rule for %q has no options", e.Path, clientLabel(c.CIDR))
		}
		for _, o := range c.Options {
			// 第五十六輪覆核(S1):除了會破壞 exports 格式的空白/逗號/括號,
			// 也擋掉 < > " ' 這些 HTML 標記字元。前端顯示 export 選項那格已經改成
			// esc() 了(才是真正的防線),這裡多擋一層 defense-in-depth,讓一個
			// 合法的 NFS 選項本來就不該出現的字元進不了 state。
			if hasControlChars(o) || strings.ContainsAny(o, " \t,()<>\"'") {
				return fmt.Errorf("nfs export %q: option %q contains characters that are not allowed in an NFS option (spaces, commas, parentheses, angle brackets, or quotes)", e.Path, o)
			}
		}
	}
	return nil
}

func clientLabel(cidr string) string {
	if cidr == "" {
		return "*"
	}
	return cidr
}

const exportsTemplate = `# 由 GoNAS 自動產生，請勿手動修改 —— 修改請透過 Web UI 或 API。
{{range .}}{{$path := .Path}}{{range .Clients}}{{$path}} {{clientLabel .CIDR}}({{join .Options ","}})
{{end}}{{end}}`

var exportsTmpl = template.Must(template.New("gonas.exports").Funcs(template.FuncMap{
	"join":        strings.Join,
	"clientLabel": clientLabel,
}).Parse(exportsTemplate))

// GenerateExportsConfig 依 export 清單產生 /etc/exports 格式的內容,
// 放進 /etc/exports.d/gonas.exports(現代 nfs-utils 支援的 drop-in 目錄,
// 不需要碰系統原本的 /etc/exports)。
func GenerateExportsConfig(exports []Export) (string, error) {
	for _, e := range exports {
		if err := e.Validate(); err != nil {
			return "", fmt.Errorf("refusing to generate nfs exports config: %w", err)
		}
	}
	var buf bytes.Buffer
	if err := exportsTmpl.Execute(&buf, exports); err != nil {
		return "", fmt.Errorf("rendering exports config: %w", err)
	}
	return buf.String(), nil
}

// ReloadNFS 重新讀取匯出清單並套用，不需要重啟 nfs-server(重啟會讓所有
// 已掛載的用戶端暫時斷線)。
func ReloadNFS(ctx context.Context, r cmdrunner.Runner) error {
	if _, err := r.Run(ctx, "exportfs", "-ra"); err != nil {
		return fmt.Errorf("reloading nfs exports: %w", err)
	}
	return nil
}
